services:
  - type: web
    name: django-web-service
    env: python
    plan: free
    buildCommand: 
      - pip install -r requirements.txt
      - python manage.py collectstatic --noinput
      - python manage.py migrate
    startCommand: gunicorn your_project_name.wsgi:application
    envVars:
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'your-domain.onrender.com'
      - key: DATABASE_URL
        fromDatabase:
          name: your-database
          property: connectionString
      - key: SECRET_KEY
        fromVault: your-vault/your-secret-key
    staticPublishPath: staticfiles
    routes:
      - type: rewrite
        source: media/(.*)
        destination: media/$1
