# Generated by Django 5.0.2 on 2024-06-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='annee',
            field=models.IntegerField(default=0),
        ),
    ]
