# Generated by Django 5.0.2 on 2024-06-27 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_examen_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='sujet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='app.sujet'),
        ),
    ]
