# Generated by Django 5.0.2 on 2024-06-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profil_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='image',
            field=models.ImageField(default='media/profil_picture/IMG_20240627_164802_770_70oVlNG.jpg', upload_to=''),
        ),
    ]
