# Generated by Django 5.0.2 on 2024-06-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_examen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='image',
            field=models.ImageField(default='mg/IMG_20240627_164802_770_70oVlNG.jpg', upload_to=''),
        ),
    ]
