# Generated by Django 5.0.2 on 2024-06-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_examen_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
