# Generated by Django 5.0.2 on 2024-06-29 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_examen_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='like',
        ),
        migrations.AddField(
            model_name='examen',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='aimes', to=settings.AUTH_USER_MODEL),
        ),
    ]
